- README.md
> Please include a summary of the change(s)/feature(s). (**Remove this text in your PR**)
> If there are any dependency changes, they are to be listed here too. (**Remove this text in your PR**)
- *[Example]* Adds Pull Request template
> If any issues have been fixed/implemented, include them here. (**Remove this text in your PR**)
- *[Example]* Closes #0
> Remerdy1 readme patch 1

- .vscode/extensions.json
- README.md
- app.js
- db.js
- package-lock.json
- package.json
- routes/pageRoutes.js
- routes/userRoutes.js
Updated file structure
Updated Readme to include instructions on setting up local db
Connection to local database 
Completed login & signup routes
> Remy signup route

- package-lock.json
- routes/userRoutes.js
> Better protect against SQL Injection
> Remy prevent sql injection

- routes/userRoutes.js
- Implements a Chaining Operator when checking for white space.
- This is because, as is, the `trim()` method is being called before validating the fields, so if the field is left empty, then an error is thrown.
> Chaining Operator Implementation

- app.js
- db.js
- routes/accountRoutes.js
Added routes for user to change their password and delete their account
> Routes for changing password and deleting account

- app.js
- routes/productRoutes.js
- Implements `GET /products/:id` method - Returns all known information about a product from its ID.
- Implements `GET /products` method - Returns all known information about every valid product.
- Valid refers to the product having enough stock, if this method is being used to display all store products, then this is the best way to go about it, but if not then it should probably also return products that do not have enough stock.
- Implements `POST /products` method - Creates a new product from [name, description, category, cost, shipping_cost, image, quantity].
- Implements `PATCH /products/:id` method - Updates an existing product.
- This method should not have empty fields passed to because it will override the existing fields.
- Implements `DELETE /products/:id` method - Deletes an …
> Product Route

- app.js
- routes/orderRoutes.js
- Implements `GET /orders/:id` method - Returns all known information about an order from its ID.
- Implements `GET /orders/search/:user` method - Returns all known orders of a user.
- Implements `POST /orders/:id` method - Creates a new order from [user_id, product_id, date, address, postcode, order_total].
- This will likely conflict with #12, I will fix the conflicts once the other PR has been merged.
> Order Route

- middleware/auth.js
- routes/accountRoutes.js
- routes/orderRoutes.js
- routes/productRoutes.js
- Implements middleware that ensures some routes are validated with a token before any action is taken.
- This is currently being used within the account, product and order routes.
- Should be used, in the future, with admin accounts and other routes.
> Authentication Middleware

- public/css/contactus.css
- views/contactus.ejs
> Dawud addedcomments

- public/css/myOrders.css
- views/myOrders.ejs
> Created my orders page and css
> Created my orders page

- public/css/home.css
- views/HomePage.ejs
- views/MensPage.ejs
- views/ProductUpClose.ejs
- views/WomensPage.ejs
- Wrote HomePage when enter the website, men and womens page and product up close to add it basket
> Kylian home page

- package-lock.json
- public/css/aboutus.css
- public/css/contactus.css
- public/css/login.css
- public/css/style.css
- public/images/menu-icon.svg
- public/js/nav.js
- routes/pageRoutes.js
- routes/userRoutes.js
- views/aboutus.ejs
- views/contactus.ejs
- views/index.ejs
- views/login.ejs
- views/partials/head.ejs
- views/partials/nav.ejs
- views/signup.ejs
- Implement Navbar
- Navbar resizes on mobile devices
- Dropdown menu for account details 
- Made css more consistent across pages
> Remy navbar

- app.js
- middleware/adminauth.js
- middleware/auth.js
- package-lock.json
- package.json
- public/css/adminpanel.css
- public/js/admin.js
- public/js/adminpanel.js
- routes/accountRoutes.js
- routes/orderRoutes.js
- routes/pageRoutes.js
- routes/productRoutes.js
- routes/userRoutes.js
- views/admin/addproduct.ejs
- views/admin/adminpanel.ejs
- views/admin/listorderproducts.ejs
- views/admin/listorders.ejs
- views/admin/listproducts.ejs
- views/admin/listusers.ejs
- views/admin/updateproduct.ejs
- views/admin/updateuser.ejs
- views/partials/sidebar.ejs
- Implemented several admin routes and pages.
- Admins can list all users and all products (via their base admin page)
- Alternatively, admins can list all users, all products, all orders and all order products separately.
- Additionally, they can edit users and products, as well as create new products.
- A bunch of page routes have been setup to fetch data when links are called.
- Implemented new authentication for admin methods, that will find the users role (from their token) and decide whether or not they should have access to the page.
- Base page is located at <host>/admin
- Here the user can view a list of recent users and recent products.
- Sidebar implementation has been added for the user to traverse the page.
- User Management -> List Users
- Lists every stored user.
- Allows …
> Admin Account

- app.js
- public/css/adminpanel.css
- public/js/admin.js
- public/js/checkout.js
- routes/accountRoutes.js
- routes/basketRoutes.js
- routes/orderRoutes.js
- routes/pageRoutes.js
- routes/productRoutes.js
- views/ProductUpClose.ejs
- views/admin/addproduct.ejs
- views/admin/listorderproducts.ejs
- views/admin/listorders.ejs
- views/admin/listproducts.ejs
- views/admin/listusers.ejs
- views/admin/updateproduct.ejs
- views/admin/updateuser.ejs
- views/basket.ejs
- views/checkout.ejs
- views/myOrders.ejs
- views/partials/nav.ejs
- Made changes to fix parts of the page (mainly the admin pages)
- Implemented the basket, which lists all of the users orders.
- (Adds a new database to record this basket)
> Basket + Fixes

- routes/pageRoutes.js
- views/admin/listorderproducts.ejs
- views/admin/listorders.ejs
- Fixes list order (admin page) not displaying orders properly.
- Fixes displaying products of an order.
> Fix list order not showing

- public/css/aboutus.css
- routes/pageRoutes.js
- views/ProductUpClose.ejs
- views/aboutus.ejs
- views/admin/addproduct.ejs
- views/admin/adminpanel.ejs
- views/admin/listorderproducts.ejs
- views/admin/listorders.ejs
- views/admin/listproducts.ejs
- views/admin/listusers.ejs
- views/partials/nav.ejs
- views/partials/sidebar.ejs
-  Added navigation between 
- Fixed styling on about us 
- Cleaned up routes
> Remy checkout

- public/js/checkout.js
- routes/basketRoutes.js
- routes/orderRoutes.js
- routes/pageRoutes.js
- views/checkout.ejs
- views/myOrders.ejs
- Allows the user to checkout their basket.
- Saves their order to the database.
- Clears the basket once the checkout has been saved.
> Added checkout implementation

- public/css/index.css
> prevent homepage overflow

- public/js/admin.js
- public/js/checkout.js
- routes/pageRoutes.js
- views/aboutus.ejs
- Removed `localhost` references when redirecting.
- Added redirect to Contact button on the about us page.
- Fixed wrong token being used for certain methods.
> Host Fixes

- middleware/auth.js
- public/css/myOrders.css
- public/js/checkout.js
- routes/orderRoutes.js
- routes/pageRoutes.js
- views/ProductUpClose.ejs
- views/checkout.ejs
- views/myOrders.ejs
- views/notfound.ejs
- My Orders page now lists orders as well as products
- Removed bug where checkout page signed users out 
- If no token is found user is redirected to log-in
- ~~Added "page not found" for products that don't exist~~
- Non-existent routes redirect to home page
- Styling for MyOrders page needs fixing
> Remy breaks orders
